### ISSUE TITLE
memory consumption keeps increasing and CUDA out of memory.

### ISSUE THREAD

**Issue by vietvo89** [Yu-Fangxu/COLD-Attack#18]
Hi, I tried to run your code and reproduce your results. However, when running, the GPU consumption keeps increasing. I have one 48GB GPU and it is insufficient to run your code. Is this normal or is there something I can change to make your code work with my GPU?

**Comment by Yu-Fangxu** [comment]
Hi, 
did you try to reduce the batch_size and the length? 48GB should be enough. I see you have addressed this issue.

**Comment by vietvo89** [comment]
Hi @Yu-Fangxu , I have not addressed the issue. Different losses are `nan` after running for a few iterations, as I reported. I then terminated the running to investigate it. I tried 2 x 48 GB, but the issue remained. Reducing the batch size just helped the running last longer (more iterations but not done an attack).

**Comment by Yu-Fangxu** [comment]
Strangely, I just tested it on my server and it does not have this problem. Do you use multiple GPUs for running? We are not supporting that. 
Also, do you use the provided configuration of the environment?

**Comment by vietvo89** [comment]
I used a single GPU first and then multiple GPUs. Both had the same problems. About the configuration of the environment, do you mean all the packages installed and used in the environment?

```
Package                   Version
------------------------- -----------
absl-py                   2.1.0
accelerate                1.3.0
aiofiles                  23.2.1
aiohappyeyeballs          2.4.6
aiohttp                   3.11.12
aiosignal                 1.3.2
alembic                   1.14.1
altair                    5.5.0
anyio                     4.8.0
asttokens                 2.0.5
async-timeout             5.0.1
attrs                     25.1.0
banal                     1.0.6
Brotli                    1.0.9
certifi                   2024.6.2
charset-normalizer        2.0.4
click                     8.1.8
comm                      0.2.1
contourpy                 1.2.1
cycler                    0.12.1
dataset                   1.6.2
datasets                  3.2.0
debugpy                   1.6.7
decorator                 5.1.1
dill                      0.3.8
distro                    1.9.0
docker-pycreds            0.4.0
einops                    0.8.1
exceptiongroup            1.2.0
executing                 0.8.3
fastapi                   0.115.8
ffmpy                     0.5.0
filelock                  3.15.4
fonttools                 4.53.0
frozenlist                1.5.0
fschat                    0.2.20
fsspec                    2024.6.1
gitdb                     4.0.12
GitPython                 3.1.44
gradio                    3.50.2
gradio_client             0.6.1
greenlet                  3.1.1
h11                       0.14.0
httpcore                  1.0.7
httpx                     0.28.1
huggingface-hub           0.28.1
idna                      3.7
importlib_resources       6.5.2
ipykernel                 6.28.0
ipython                   8.25.0
ipywidgets                8.1.5
jedi                      0.18.1
Jinja2                    3.1.5
jiter                     0.8.2
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter_client            8.6.0
jupyter_core              5.7.2
jupyterlab_widgets        3.0.13
kiwisolver                1.4.5
latex2mathml              3.77.0
Mako                      1.3.9
markdown-it-py            3.0.0
markdown2                 2.5.3
MarkupSafe                2.1.5
matplotlib                3.9.0
matplotlib-inline         0.1.6
mdurl                     0.1.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
ml_collections            1.0.0
mpmath                    1.3.0
multidict                 6.1.0
multiprocess              0.70.16
narwhals                  1.26.0
nest-asyncio              1.6.0
networkx                  3.4.2
nh3                       0.2.20
nltk                      3.8.1
numpy                     1.26.4
openai                    1.63.2
opencv-python             4.10.0.84
orjson                    3.10.15
packaging                 23.2
pandas                    2.2.2
parso                     0.8.3
patsy                     0.5.6
peft                      0.14.0
pexpect                   4.8.0
pillow                    10.3.0
pip                       24.0
platformdirs              3.10.0
prompt-toolkit            3.0.43
propcache                 0.2.1
protobuf                  5.29.3
psutil                    5.9.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   19.0.0
pydantic                  1.10.21
pydub                     0.25.1
Pygments                  2.15.1
pyparsing                 3.1.2
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-multipart          0.0.20
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     25.1.2
referencing               0.36.2
regex                     2024.11.6
requests                  2.32.2
rich                      13.9.4
rpds-py                   0.22.3
safetensors               0.4.3
scikit-learn              1.6.1
scipy                     1.11.4
seaborn                   0.13.2
segment_anything          1.0
semantic-version          2.10.0
sentencepiece             0.2.0
sentry-sdk                2.21.0
setproctitle              1.3.4
setuptools                69.5.1
shortuuid                 1.0.13
six                       1.16.0
smmap                     5.0.2
sniffio                   1.3.1
SQLAlchemy                1.4.54
stack-data                0.2.0
starlette                 0.45.3
statsmodels               0.14.2
svgwrite                  1.4.3
sympy                     1.13.1
threadpoolctl             3.5.0
tiktoken                  0.8.0
timm                      0.6.13
tokenizers                0.13.3
torch                     2.6.0
torchaudio                0.13.1
torchvision               0.14.1
tornado                   6.4.1
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.28.1
triton                    3.2.0
typing_extensions         4.11.0
tzdata                    2024.1
urllib3                   2.2.2
uvicorn                   0.34.0
wandb                     0.18.7
wavedrom                  2.0.3.post3
wcwidth                   0.2.5
websockets                11.0.3
wheel                     0.43.0
widgetsnbextension        4.0.13
xxhash                    3.5.0
yarl                      1.18.3
```

**Comment by vietvo89** [comment]
And

```
$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
allowlist_channels: []
always_copy: False
always_softlink: False
always_yes: None
anaconda_anon_usage: True
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: True
bld_path: 
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: flexible
channel_settings: []
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: /opt/anaconda3/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults: 
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local: 
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.11
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env}) 
envs_dirs:
  - /opt/anaconda3/envs
  - /.conda/envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
experimental: []
extra_safety_checks: False
fetch_threads: 5
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
no_plugins: False
non_admin_enabled: True
notify_outdated_conda: True
number_channel_notices: 5
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - /opt/anaconda3/pkgs
  -/.conda/pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: /opt/anaconda3
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: None
signing_metadata_url_base: None
solver: classic
solver_ignore_timestamps: False
ssl_verify: True
subdir: linux-64
subdirs:
  - linux-64
  - noarch
target_prefix_override: 
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
```

**Comment by Jus1mple** [comment]
The same problem. Is there any available solution? Or this is just the env issue? We should exactly match the env config as the requirement file?

**Comment by Jus1mple** [comment]
Back! I tried transformers==4.43.1 and it works! LOL

**Comment by vietvo89** [comment]
@Jus1mple , if you have solved this problem, did you observe the same issue as reported in https://github.com/Yu-Fangxu/COLD-Attack/issues/19?

**Comment by Jus1mple** [comment]
> [@Jus1mple](https://github.com/Jus1mple) , if you have solved this problem, did you observe the same issue as reported in [#19](https://github.com/Yu-Fangxu/COLD-Attack/issues/19)?

@vietvo89 Nah, I just followed the instructions in README and executed COLD-Attack using different datasets successfully. Maybe there are other reasons leading to issue #19
